ga4gh/vrs-python

README.rst, src/ga4gh/vrs/_internal/models.py
Needed update to enable correct validation of ChromosomeLocation objects with VRS-python
=> update spec and call to it in tests

src/ga4gh/core/_internal/jsonschema.py
This addresses ga4gh/vrs#295 in vrs-python.
=> update VRS and apply VRS patch for pjs

src/ga4gh/vrs/extras/translator.py, tests/conftest.py, tests/extras/test_dataproxy.py, tests/extras/test_translator.py, tests/test_vcr.py
Merged #56 prematurely. Reverting.
=> Revert "Fix bug in _from_hgvs when using SeqRepoDataProxy"

src/ga4gh/vrs/extras/localizer.py, src/ga4gh/vrs/extras/translator.py, src/ga4gh/vrs/normalize.py, tests/extras/test_translator.py, tests/test_vrs.py
Closes #69 
- SimpleInterval --> Sequence Interval
- SequenceState --> LiteralSequenceExpression
I'm unable to update the notebooks due to #61
=> Use SequenceInterval and LiteralSequenceExpression in ga4gh.vrs.extras

src/ga4gh/vrs/extras/translator.py, tests/extras/cassettes/test_to_spdi.yaml, tests/extras/test_translator.py
Will open PR once #76 is addressed. This PR fixes a missed bug after updating VRS models + adds test for the method.
=> Issue 77: Fix TypeError in _to_spdi

src/ga4gh/vrs/extras/translator.py
Closes #88 
@andreasprlic It appears that the vrs-python 0.7 branch is working fine for the vrs 1.2 branch. So I assume that #88 was just regarding main?
=> Issue 88: Update vrs submodule + remove type from models in translator

README.md, notebooks/Terra.ipynb
Building on #108 from @korikuzma — addressing request for additional info from @ahwagner
=> Add instructions to Terra notebook 

src/ga4gh/vrs/extras/vcf_annotation.py, tests/extras/test_vcf_annotation.py
=> feat: vcf annotation to allow assembly param (#125)

tests/extras/cassettes/test_annotate_vcf.yaml, tests/extras/test_vcf_annotation.py
#126 broke GitHub actions tests. This gets gh action tests to pass
=> fix: VCF Annotation tests use REST dp

src/ga4gh/vrs/extras/vcf_annotation.py, tests/extras/cassettes/test_annotate_vcf.yaml, tests/extras/test_vcf_annotation.py
=> feat: vcf annotator optionally allows output vcf/pickle

.gitignore, src/ga4gh/vrs/__init__.py, src/ga4gh/vrs/extras/vcf_annotation.py, tests/extras/cassettes/test_get_vrs_object_invalid_input.yaml, tests/extras/test_vcf_annotation.py
Close #132 
Notes:
- Handled exceptions that might not be raised with the current version, but as a safety net for future versions so I included them in this PR. 
- Added log file to capture log statements. Let me know if I should rename the log file or if I should be using different log levels for the exceptions.
=> feat: VCF Annotator handles invalid input (#132)

src/ga4gh/vrs/extras/vcf_annotation.py
=> change: remove VCF ID from key in pickle file for vcf annotation

.gitignore, src/ga4gh/vrs/__init__.py, src/ga4gh/vrs/extras/vcf_annotation.py, tests/extras/cassettes/test_get_vrs_object_invalid_input.yaml, tests/extras/test_vcf_annotation.py
Close #132 , Close #135
These were already reviewed (#134 , #136), but the PR didn't auto update to the main branch.
=> VCF Annotator handles invalid input + remove VCF ID from key in pickle file for vcf annotation

src/ga4gh/vrs/extras/vcf_annotation.py
Close #145 
@wesleygoar Let me know if we need to add more logs somewhere else
=> Add more log statements to VCF Annotator

src/ga4gh/vrs/extras/translator.py, tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181220del-expected2].yaml, tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181230_55181231insGGCT-expected3].yaml, tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181320A>T-expected1].yaml, tests/extras/cassettes/test_hgvs[NC_000013.11:g.32316467dup-expected5].yaml, tests/extras/cassettes/test_hgvs[NC_000013.11:g.32331093_32331094dup-expected4].yaml, tests/extras/cassettes/test_hgvs[NC_000013.11:g.32936732=-expected0].yaml, tests/extras/cassettes/test_hgvs[NM_001331029.1:n.872A>G-expected6].yaml, tests/extras/cassettes/test_hgvs[NM_181798.1:n.1263G>T-expected7].yaml, tests/extras/cassettes/test_to_spdi.yaml, tests/extras/test_translator.py
=> feat: include VRS location digest if identify is True

setup.cfg
=> build: fix broken long_description reference

.binder/postBuild, .binder/requirements.txt, .binder/runtime.txt
Address #175 for 0.9 branch
https://hub.gke2.mybinder.org/user/ga4gh-vrs-python-gta1nd1o/lab
=> fix: mybinder build 

.binder/requirements.txt, .binder/runtime.txt
Address #175 for 0.8 branch
https://hub.gke2.mybinder.org/user/ga4gh-vrs-python-ngrv0vp3/lab
=> fix: mybinder build

README.md
=> docs: update readme for vrs branch tracking

.github/workflows/python-cqa.yml, .github/workflows/release.yml, .travis.yml, setup.cfg
Close #199
Addresses #199 for main branch
=> build: support python >= 3.8

README.md
Addresses #190 for 0.9 branch
@larrybabb was this the issue?
=> docs: update pip installation + fix typos

README.md
=> docs: update pip installation + fix typos (#207)

tests/extras/cassettes/test_rest_dp_to_hgvs[NC_000007.14:g.55181220del-vo_as_dict2].yaml, tests/extras/cassettes/test_rest_dp_to_hgvs[NC_000007.14:g.55181230_55181231insGGCT-vo_as_dict3].yaml, tests/extras/cassettes/test_rest_dp_to_hgvs[NC_000007.14:g.55181320A>T-vo_as_dict1].yaml, tests/extras/cassettes/test_rest_dp_to_hgvs[NC_000013.11:g.32316467dup-vo_as_dict5].yaml, tests/extras/cassettes/test_rest_dp_to_hgvs[NC_000013.11:g.32331093_32331094dup-vo_as_dict4].yaml, tests/extras/cassettes/test_rest_dp_to_hgvs[NC_000013.11:g.32936732=-vo_as_dict0].yaml, tests/extras/cassettes/test_rest_dp_to_hgvs[NM_001331029.1:n.872A>G-vo_as_dict6].yaml, tests/extras/cassettes/test_rest_dp_to_hgvs[NM_181798.1:n.1263G>T-vo_as_dict7].yaml
=> test: update cassettes for variation normalizer rest dp

src/ga4gh/core/_internal/identifiers.py, src/ga4gh/core/_internal/pydantic.py, src/ga4gh/vrs/_internal/models.py, src/ga4gh/vrs/extras/variation_normalizer_rest_dp.py, src/ga4gh/vrs/normalize.py, tests/validation/test_models.py
Other cleanup and added use_enum_values to pydantic models where necessary
=> Minor changes to how direct and indirect ranges are serialized

src/ga4gh/vrs/_internal/models.py
Related to [this](https://github.com/ga4gh/vrs/issues/432) VRS issue. Want to change it now since the case will affect digests
=> fix: use camel case for copy change

README.md, src/ga4gh/core/__init__.py, src/ga4gh/vrs/__init__.py, src/ga4gh/vrs/_internal/models.py
Also removed some references to VRSATILE schema dir
=> refactor: replace pkg_resources with importlib.metadata

src/ga4gh/vrs/extras/translator.py, tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181220del-expected2].yaml, tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181230_55181231insGGCT-expected3].yaml, tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181320A>T-expected1].yaml, tests/extras/cassettes/test_hgvs[NC_000013.11:g.32316467dup-expected5].yaml, tests/extras/cassettes/test_hgvs[NC_000013.11:g.32331093_32331094dup-expected4].yaml, tests/extras/cassettes/test_hgvs[NC_000013.11:g.32936732=-expected0].yaml, tests/extras/cassettes/test_hgvs[NM_001331029.1:n.872A>G-expected6].yaml, tests/extras/cassettes/test_hgvs[NM_181798.1:n.1263G>T-expected7].yaml, tests/extras/test_translator.py
- Also raises a TypeError if `vo.location.sequenceReference` is NOT a SequenceReference
=> fix: _to_hgvs using wrong vars for hgvs.location.Interval

tests/extras/cassettes/test_from_gnomad.yaml, tests/extras/test_translator.py
close #245 
Notes:
- I already updated _from_gnomad in #241 , so this PR just creates more tests for the different kinds of gnomad expressions
- Updated normalize param in other tests, since default was `False`. This highlights the need for #231
=> tests: add tests for tlr._from_gnomad

setup.cfg, src/ga4gh/vrs/_internal/models.py
Close #235 More info: https://docs.pydantic.dev/2.3/errors/usage_errors/#root-model-extra
Glad it was a simple fix
=> build: unpin pydantic version

docker-compose.yml, setup.cfg, src/ga4gh/vrs/_internal/models.py
=> chore: update uta docker image to uta_20210129b

src/ga4gh/vrs/extras/translator.py, src/ga4gh/vrs/extras/vcf_annotation.py, tests/conftest.py, tests/extras/cassettes/test_from_hgvs_cx[NC_000013.11:g.26440969_26443305del-CopyChange.EFO_0030069-expected0].yaml, tests/extras/test_allele_translator.py, tests/extras/test_cnv_translator.py, tests/extras/test_variation_normalizer_rest_dp.py, tests/extras/test_vcf_annotation.py
* Renames previous Translator to AlleleTranslator
* translate_from accepts kwargs
* CnvTranslator only supports _from_hgvs
=> feat!: Add CnvTranslator

src/ga4gh/vrs/extras/translator.py, tests/extras/cassettes/test_from_gnomad.yaml, tests/extras/test_allele_translator.py, tests/extras/test_vcf_annotation.py
Addresses #275 for 2-alpha branch
Cherry-picked [0419979](https://github.com/ga4gh/vrs-python/commit/0419979799a2c13a78a5b9a2066511a8263e3f30) commit (had to resolve some conflicts)
=> fix: gnomad_re should accept all nucleotide characters for ref/alt

.github/workflows/release.yml
I hope this fixes it? Using single quotes in the past for this step worked
=> cicd: use single quotes in if condition for branch name

README.md
Updated the python version from 3.7 to 3.10.
Provided description about running the notebook on VS Code.
=> docs: Update README for running notebooks

README.md
* Updated the python version from 3.7 to 3.10
* Provided description about running the notebook on VS Code
* Included how to run notebooks in Terra with cherry-picked commit
=> docs: Update README for running notebooks (#286)

notebooks/PGx.ipynb
=> fix: update PGx.ipynb mybinder url

.gitmodules
* Now points to vrs 2.x branch
Chore for conventional commit?
=> chore: update submodules

README.md
=> docs: update uta docker image in readme

README.md
* Order change in readme
* Fixed readme order
* Added venv changes
* Readme changes
=> docs: change order in readme (#294)

MANIFEST.in, README.md, setup.cfg
Grouping this together to reduce the notifications that I'm creating for @korikuzma 
* Remove references to Travis CI
* Remove stuff related to VRSATILE
I think this is everything? Actually close #223 this time?
=> chore: remove more unused stuff

src/ga4gh/vrs/extras/translator.py, tests/extras/cassettes/test_rle_seq_limit.yaml, tests/extras/test_allele_translator.py
close #344 . Setting as high priority since @quinnwai said it was blocking
@quinnwai The reason why your example was failing is because the `len(alt) > 50`, where 50 was the limit we had set. This PR allows `rle_seq_limit` to be passed
=> fix: add rle_seq_limit to AlleleTranslator

src/ga4gh/vrs/normalize.py
This PR refactors the normalization implementation for coherency and alignment with the algorithm clarifications in https://github.com/ga4gh/vrs/pull/466.
It includes factorization improvements for scalability of alternate sequence checks in large insertions.
These changes are not expected to impact computed digests.
=> simplify normalization implementation

docker-compose.yml
=> fix: add password to docker-compose.yml for uta service

README.md
I haven't tried installing UTA locally, but this is what I noticed when cloning the repo, installing a local seqrepo, + testing out psql command
=> docs: update readme (install seqrepo, psql cmd, + submodules)

Makefile, notebooks/getting_started/README.md
=> feat: add make command (`nbready`) to create jupyter notebook venv

src/ga4gh/core/_internal/models.py
* Removes Information Entity, Activity, Contribution, Agent, Document, Method, + Record Metadata pydantic models
=> chore!: update vrs/gks-common submodules

src/ga4gh/vrs/extras/vcf_annotation.py
making a few small housekeeping PRs local to the VCF module because I'm taking a look at it this morning
~...could also expand this one to the rest of the package possibly~ <- no this is actually a nightmare
=> chore: update VCF annotator type annotations for 3.10-12

tests/extras/cassettes/test_hgvs[NC_000013.11:g.32316467dup-expected5].yaml, tests/extras/cassettes/test_hgvs[NC_000013.11:g.32331093_32331094dup-expected4].yaml, tests/extras/cassettes/test_hgvs[NC_000013.11:g.32936732=-expected0].yaml, tests/extras/cassettes/test_hgvs[NC_000019.10:g.289464_289465insCACA-expected8].yaml, tests/extras/cassettes/test_hgvs[NC_000019.10:g.289485_289500del-expected9].yaml, tests/extras/cassettes/test_hgvs[NM_001331029.1:c.722A>G-expected6].yaml, tests/extras/cassettes/test_hgvs[NM_181798.1:c.1007G>T-expected7].yaml, tests/extras/cassettes/test_rle_seq_limit.yaml
bioutils was recently updated, which caused tests to fail. this change updates the cassettes to get tests to pass
close #462
=> test: re-run hgvs cassettes

README.md
=> docs: clarify python 3.12 requirement for contributors

pyproject.toml
=> build(test): pin vcrpy>=7.0.0 + remove urllib3 from optional dev deps

.gitmodules, src/ga4gh/core/models.py, src/ga4gh/vrs/extras/translator.py, src/ga4gh/vrs/models.py, tests/extras/cassettes/test_from_hgvs_cx[NC_000013.11:g.26440969_26443305del-complete genomic loss-expected0].yaml, tests/extras/cassettes/test_from_spdi.yaml, tests/extras/test_cnv_translator.py, tests/validation/test_models.py
close #515 
https://github.com/ga4gh/gks-core/compare/257a57c...1.0.0
https://github.com/ga4gh/vrs/compare/2.0.0-snapshot.2025-02.2...2.0.1
=> feat!: update models to VRS 2.0.1

README.md
Added text in the README to describe how do overcome a port collision on setting up local UTA and SeqRepo resources.
=> Docker compose docs

pyproject.toml, src/ga4gh/core/models.py, src/ga4gh/vrs/models.py
=> chore(lint): enforce ruff pyupgrade (UP) rules

pyproject.toml
=> build: temporarily pin hgvs

notebooks/getting_started/5_Exploring_the_CnvTranslator.ipynb, notebooks/getting_started/6_Upcoming_features.ipynb
close #575 
* copy_change use free text string instead of efo code curie
* update field names in sequence reference
=> fix(notebooks): update notebooks to use vrs 2.x

pyproject.toml
=> build: pin pysam 0.23.0 to avoid pytest-cov bug
