- src/ga4gh/vrs/extras/translator.py
- tests/conftest.py
- tests/extras/test_dataproxy.py
- tests/extras/test_translator.py
- tests/test_vcr.py
`_from_hgvs` works when using SeqRepoRestDataProxy, but failed when using SeqRepoDataProxy for identity and dup HGVS expressions. This failed because `fetch_uri` expects a namespace and accession (ex: refseq:NM_12345) and `sv.ac` would only provide an accession (ex: NM_12345), so switched to using `sequence_id` as the identifier. 
> def fetch_uri(self, uri, start=None, end=None):
"""fetch sequence for URI/CURIE of the form namespace:alias, such as
NCBI:NM_000059.3.
>   
>        """
>    
>       namespace, alias = uri_re.match(uri).groups()
>       AttributeError: 'NoneType' object has no attribute 'groups'
Added tests for both SeqRepoRestDataProxy and SeqRepoDataProxy.
> Fix bug in _from_hgvs when using SeqRepoDataProxy

- Makefile
This was commented in #74 . Unsure if we wanted to make this change there or in a new PR. Since no change has been made, I decided just to create a new PR. I know @ahwagner is going to make a new release soon for our team's needs, so it would also be nice to ensure all tests pass before doing so.
> Update SEQREPO_ROOT_DIR in Makefile to fix failing test

- src/ga4gh/vrs/extras/translator.py
- tests/extras/cassettes/test_hgvs[NM_001331029.1:n.872A>G-expected6].yaml
- tests/extras/cassettes/test_hgvs[NM_181798.1:n.1263G>T-expected7].yaml
- tests/extras/test_translator.py
Resolves #73 
I chose to validate the four types of prefixes that we allow in `def ir_stype(a):`, NM, NP, NG, and NC.
> Add error handling for HGVSDataNotAvailableError during HGVS translation

- .github/workflows/release.yml
Creates PyPI releases from tags added to commits on the main branch.
* GitHub syntax filters are a little more constrained than normal regex so it's difficult to enforce the [entire PEP440 versioning syntax](https://stackoverflow.com/a/38020327) -- the provided filter just does a pretty lax check for tags that look like semantic versioning
* Someone (@ahwagner) will need to supply PyPI API tokens as GitHub secrets named PYPI_API_TOKEN and TEST_PYPI_API_TOKEN
> Add release workflow action

- .github/workflows/python-cqa.yml
- src/ga4gh/vrs/extras/translator.py
- tests/extras/test_translator.py
fix: support SequenceState with LiteralSequenceExpression and SimpleInterval with SequenceInterval
This PR is 0.7->0.7
There was the same PR for main : https://github.com/ga4gh/vrs-python/pull/86
> fix: support SequenceState, SimpleInterval p.2 - for 0.7

- src/ga4gh/core/_internal/identifiers.py
- tests/test_vrs.py
Close #116 
VRS docs for computing digests will be updated in [this](https://github.com/ga4gh/vrs/issues/410) issue
> feat: digests take ordered property in arrays into consideration (#116)

- docs/extras/README.md
- docs/extras/vcf_annotator.md
- setup.cfg
- src/ga4gh/vrs/extras/vcf_annotation.py
- tests/extras/test_vcf_annotation.py
Close #122
Notes:
- Replaces argparse with click
- Allows users to select from either local or REST SeqRepo Data Proxy
- Cleans up the VCFAnnotator code
> feat: VCFAnnotator accepts both seqrepo dps + clean up

- README.md
Close #140 
(Accidentally named my branch after the wrong issue)
Confirmed this with @ahwagner :
- Yank PyPI releases for vrs-python versions >= 0.8.4dev0
- Use 0.9.0-devX for releases on metaschema-udpate branch
> docs: update README for metaschema-update branch / releases

- .pre-commit-config.yaml
- README.md
- setup.cfg
Close #138 
Adds pre-commit hook so that new changes must be above the pylint fail under score defined in `.pylintrc`. Many times, we've seen our GitHub Action fail due to pylint. This should fix this and help us resolve warnings before we're able to commit our changes!
You will need to make sure to run `pre-commit install`
> feat: add pre-commit hook for pylint

- notebooks/Extras.ipynb
- notebooks/HGVS Translation.ipynb
- src/ga4gh/vrs/extras/translator.py
- src/ga4gh/vrs/extras/vcf_annotation.py
- tests/extras/cassettes/test_annotate_vcf.yaml
- tests/extras/cassettes/test_from_beacon.yaml
- tests/extras/cassettes/test_from_gnomad.yaml
- tests/extras/cassettes/test_from_hgvs.yaml
- tests/extras/cassettes/test_hgvs[NC_000013.11:g.32936732=-expected0].yaml
- tests/extras/cassettes/test_to_spdi.yaml
- tests/extras/test_translator.py
- tests/extras/test_vcf_annotation.py
Close #147 
- Update regex for input str
- Based off of the [The Variant Call Format Specification](https://samtools.github.io/hts-specs/VCFv4.3.pdf) that @wesleygoar sent me:
- Validate that expected reference sequence matches actual reference sequence
- Cassettes were automatically generated
- Updated translator test to match latest [VRS docs example](https://vrs.ga4gh.org/en/latest/impl-guide/example.html) since the previous test had an invalid reference sequence
> feat: Add validation to _from_gnomad in translator

- .pylintrc
> chore: remove pylint warning for overgeneral-exceptions

- setup.cfg
The PyPI page (https://pypi.org/project/ga4gh.vrs/) currently lacks a description because the filename provided to setuptools is old. This should fix it (checked locally with Twine)
> build: fix broken long_description reference

- .github/workflows/python-cqa.yml
Or we can just change to `on: [push, pull_request]` like we do in our other vicc repos
> ci: python-cqa should run on 0.8 branch

- src/ga4gh/vrs/extras/translator.py
- tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181220del-expected2].yaml
- tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181230_55181231insGGCT-expected3].yaml
- tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181320A>T-expected1].yaml
- tests/extras/cassettes/test_hgvs[NC_000013.11:g.32316467dup-expected5].yaml
- tests/extras/cassettes/test_hgvs[NC_000013.11:g.32331093_32331094dup-expected4].yaml
- tests/extras/cassettes/test_hgvs[NC_000013.11:g.32936732=-expected0].yaml
- tests/extras/cassettes/test_hgvs[NM_001331029.1:n.872A>G-expected6].yaml
- tests/extras/cassettes/test_hgvs[NM_181798.1:n.1263G>T-expected7].yaml
- tests/extras/test_translator.py
Close #154 . We did this in #155 for main branch, but did not do it for the 0.9 branch.
Variation Normalizer and VCF tests are expected to fail at the moment.
> feat: include VRS location digest if identify is True (0.9 branch)

- .pre-commit-config.yaml
- .pylintrc
- README.md
- setup.cfg
- src/ga4gh/core/__init__.py
- src/ga4gh/core/_internal/identifiers.py
- src/ga4gh/core/_internal/jsonschema.py
- src/ga4gh/vrs/dataproxy.py
- src/ga4gh/vrs/extras/localizer.py
- src/ga4gh/vrs/extras/translator.py
- src/ga4gh/vrs/extras/utils.py
- src/ga4gh/vrs/extras/variation_normalizer_rest_dp.py
- src/ga4gh/vrs/extras/vcf_annotation.py
- src/ga4gh/vrs/normalize.py
> cleanup: add pre-commit + resolve pylint warnings

- setup.cfg
- src/ga4gh/vrs/normalize.py
- tests/cassettes/test_normalize_allele.yaml
- tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181220del-expected2].yaml
- tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181230_55181231insGGCT-expected3].yaml
- tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181320A>T-expected1].yaml
- tests/extras/cassettes/test_hgvs[NC_000013.11:g.32316467dup-expected5].yaml
- tests/extras/cassettes/test_hgvs[NC_000013.11:g.32331093_32331094dup-expected4].yaml
- tests/extras/cassettes/test_hgvs[NC_000013.11:g.32936732=-expected0].yaml
- tests/extras/cassettes/test_hgvs[NM_001331029.1:n.872A>G-expected6].yaml
- tests/extras/cassettes/test_hgvs[NM_181798.1:n.1263G>T-expected7].yaml
- tests/extras/cassettes/test_to_spdi.yaml
- tests/test_vrs_normalize.py
@theferrit32 @toneillbroad I don't think RLE normalization was fully added, so this PR will close #204 . The normalize vrs test now passes and have different error messages for the translator ones that failed. The translator tests that previously passed, still pass with these changes.
@ahwagner @larrybabb The [2.0-alpha docs](https://github.com/ga4gh/vrs/blob/86cafd4b1942d78ac8c7701de6d1b33d2f8a145e/docs/source/impl-guide/normalization.rst) has Allele with LSE and RSE (which is not in 2.0-alpha). So I assumed that the LSE section is used for both LSE and RLE. In addition to @theferrit32 or @toneillbroad review, I'd like one of you to review (my brain is on low battery). 
Notes:
- Pin pydantic version to working version. v2.2+ had errors when importing models
- Updated `_normalize_allele` …
> feat: allele rle normalization + pin pydantic version

- docker-compose.yml
- setup.cfg
- src/ga4gh/core/__init__.py
- src/ga4gh/core/_internal/identifiers.py
- src/ga4gh/core/_internal/models.py
- src/ga4gh/vrs/_internal/models.py
- tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181220del-expected2].yaml
- tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181230_55181231insGGCT-expected3].yaml
- tests/extras/test_translator.py
- tests/test_vrs.py
- tests/test_vrs2.py
- tests/validation/test_models.py
Notes:
* Made use of the classes in core-source/vrs-source so we don't repeat code
* Tried to reorganize some models
* Changed enums keys to uppercase
* For ga4gh_identify/ga4gh_serialize/ga4gh_digest, let me know if there's a cleaner way to handle `SequenceReference`
* Update tests since digests changed
> feat!: update vrs 2.0-alpha models 

- docker-compose.yml
> chore: update uta docker image to uta_20210129b

- src/ga4gh/core/_internal/identifiers.py
- tests/test_vrs2.py
* ga4gh prefixes were not getting removed during serialization. SequenceReferences are the only types that do not need to be removed
> fix: identify_all method (rm ga4gh prefixes)

- .github/workflows/release.yml
close #269 (2-alpha branch)
* Followed https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
* Did not include [Signing the distribution packages](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#signing-the-distribution-packages)
* In `publish-to-pypi`, removed `if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes` since we only make a release when a tag is created.
> cicd: update release.yml to use trusted publisher

- src/ga4gh/vrs/extras/translator.py
- tests/extras/cassettes/test_from_gnomad.yaml
- tests/extras/test_translator.py
- tests/extras/test_vcf_annotation.py
> fix: gnomad_re should accept all nucleotide characters for ref/alt

- setup.cfg
- src/ga4gh/core/_internal/models.py
- src/ga4gh/vrs/_internal/models.py
Not really sure why, but when `RootModel` classes are used as attributes in Pydantic models, the `model_json_schema` method seems to get very picky about how things like descriptions and examples are provided. Specifically, it wants them under the `json_schema_extra` param -- otherwise, they won't show up in the JSON schema produced by libraries like FastAPI. This PR makes this change (which coincidentally also silences a sort of annoying warning that starts appearing in more recent Pydantic v2 versions).
> fix: ensure extra fields present in jsonschema

- setup.cfg
[This commit](https://github.com/ga4gh/vrs-python/commit/76a3c72ef869927699fa22ee73bf9830280bb2ab) introduced a dependency on `jsonschema` because it was required by `python-jsonschema-objects` but they didn't pin it themselves, for some reason. I think we can get rid of it entirely now that we're on Pydantic (or at least, tests pass and it doesn't seem to be used anywhere...)
> build(deps): remove jsonschema dependency

- src/ga4gh/core/__init__.py
- src/ga4gh/core/_internal/enderef.py
- src/ga4gh/core/_internal/identifiers.py
- src/ga4gh/vrs/_internal/enderef.py
- src/ga4gh/vrs/extras/vcf_annotation.py
- src/ga4gh/vrs/normalize.py
- tests/test_vrs2.py
See also #305
The focus of these changes is to avoid unnecessary VRS ID computation.  There are places in the code where VRS ID computation is done even when a valid VRS ID is already present:
- In `vrs_enref` and `ga4gh_enref` allow the caller to have the VRS ID returned along with the encoded object data
- Provide mechanism for a caller to have `ga4gh_identify` skip VRS ID computation if an ID already exists
The second change is intended for use in situations where the data passed to `ga4gh_identify` originates from a trusted source, such as `VCFAnnotator.annotate()` which is now decorated to skip VRS ID computation.
The combination of these changes yields approximately 20% performance improvement for VCF annotation.
> Enhancements to improve VRS computation performance

- README.md
> Enhanced installation guide

- docker-compose.yml
> chore: update test image for uta

- src/ga4gh/vrs/_internal/models.py
- tests/test_vrs2.py
> fix: use start/end constraints for `digest` and `refgetAccession` fields

- src/ga4gh/vrs/extras/translator.py
- tests/extras/cassettes/test_from_spdi.yaml
- tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181220del-expected2].yaml
- tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181230_55181231insGGCT-expected3].yaml
- tests/extras/cassettes/test_hgvs[NC_000007.14:g.55181320A>T-expected1].yaml
- tests/extras/cassettes/test_hgvs[NC_000013.11:g.32316467dup-expected5].yaml
- tests/extras/cassettes/test_hgvs[NC_000013.11:g.32331093_32331094dup-expected4].yaml
- tests/extras/cassettes/test_hgvs[NC_000013.11:g.32936732=-expected0].yaml
- tests/extras/cassettes/test_hgvs[NC_000019.10:g.289464_289465insCACA-expected8].yaml
- tests/extras/cassettes/test_hgvs[NC_000019.10:g.289485_289500del-expected9].yaml
- tests/extras/cassettes/test_hgvs[NM_001331029.1:n.872A>G-expected6].yaml
- tests/extras/cassettes/test_hgvs[NM_181798.1:n.1263G>T-expected7].yaml
- tests/extras/cassettes/test_to_spdi.yaml
- tests/extras/test_allele_translator.py
- tests/extras/test_cnv_translator.py
close #231 
@larrybabb I believe this will help with the variation-normalizer issue. 
* new kwarg (do_normalize) in translate_from methods. Set to determine if normalization should be performed
> feat!: parameterize normalize in translator

- README.md
close #368 
Ideally, in the future we will create a rtd so that our readme isn't so long
> docs: update + reorganize readme

- .github/workflows/release.yml
Our current approach can break when there are multiple branches that track the same tag:
```shell
$ echo $raw
origin/issue-380 origin/main origin/pypi-release-action origin/release origin/vcf-annotator-readme-update
$ branch=${raw##*/}
$ echo $branch
vcf-annotator-readme-update
```
@theferrit32 thanks for pointing out the multiple branches issue! I think this will fix the release action
> cicd: fix release when multiple branches track same tag

- src/ga4gh/vrs/dataproxy.py
- src/ga4gh/vrs/utils/hgvs_tools.py
> feat: add inclusion of "NT" prefixed refseq accessions to hgvs tools

- setup.cfg
- src/ga4gh/vrs/extras/translator.py
- tests/extras/cassettes/test_from_hgvs_cx[NC_000005.9:g.(90136803)_(90159675)dup-None-expected6].yaml
- tests/extras/cassettes/test_from_hgvs_cx[NC_000009.11:g.(?_108337304)_(108337428_?)del-None-expected5].yaml
- tests/extras/cassettes/test_from_hgvs_cx[NC_000013.11:g.26440969_26443305del-CopyChange.EFO_0030069-expected0].yaml
- tests/extras/cassettes/test_from_hgvs_cx[NC_000023.11:g.(31060227_31100351)_(33274278_33417151)dup-None-expected4].yaml
- tests/extras/test_cnv_translator.py
close #381 
Since we are waiting on HGVS PR to be merged, I used `main-draft` as the base branch.
> feat: cnv translator supports uncertain ranges for g. and m.

- Makefile
close #395 
* In #388 we forgot to update the commands to remove setup.py since it was removed. This commit removes references to setup.py and setup.cfg in Makefile
> fix: get `make test` to run

- src/ga4gh/core/_internal/models.py
- src/ga4gh/vrs/_internal/models.py
close #350
* constr is discouraged and will be deprecated in Pydantic 3.0. Per docs, constr returns a type, which doesn't play well with static analysis tools
https://docs.pydantic.dev/2.6/api/types/#pydantic.types.constr--__tabbed_1_1
> refactor: use Annotated with StringConstraints instead of constr

- src/ga4gh/vrs/extras/translator.py
- tests/extras/test_allele_translator.py
See #400 
Updated `_from_hgvs()` to only call `_create_allele()` is value extraction was successful. Otherwise returns `None` to indicate description could not be parsed as HGVS.
> Only attempt to create allele if values were extracted

- src/ga4gh/vrs/extras/translator.py
- src/ga4gh/vrs/utils/hgvs_tools.py
close #392 
@larrybabb sorry, i realized after I made the comment about new issue that this could have been done in #387 . For some reason, I was thinking of HgvsTools having it's own CnvTranslator
> refactor: move getting hgvs loc start/end to HgvsTools

- src/ga4gh/core/__init__.py
- src/ga4gh/core/_internal/models.py
> feat!: rename core_models to common_models

- src/ga4gh/vrs/models.py
@ahwagner this resolves the tests in your branch
> fix: f-string in `ga4gh_serialize_as_version`

- src/ga4gh/core/identifiers.py
- src/ga4gh/vrs/models.py
- tests/validation/test_models.py
Note: tests only pass for Python 3.12 due to changes in f-string implementation introduced in 3.12. These should be addressed before merge.
closes #382
> feat: VRS 1.3 digests may be computed for Alleles and Sequence Locations

- src/ga4gh/core/__init__.py
- src/ga4gh/core/identifiers.py
- src/ga4gh/vrs/models.py
- tests/validation/test_models.py
Building off of #382 and #427
* Add `PrevVrsVersion` enum to store previous versions of VRS that is supported for computing digests/identifiers
* Updates function signatures + docstrings for ga4gh digest/serialize/identifier
* Adds restrictions to `ga4gh_serialize_as_version`
* For `SequenceLocation`: `sequenceReference` must be provided and must be a valid `SequenceReference` obj
* For `Allele`: Only `LiteralSequenceExpression` and `ReferenceLengthExpression` are supported and must provide a `sequence` nonnull attribute.
> feat: add enum for `as_version` + add restrictions to `ga4gh_serialize_as_version`

- src/ga4gh/core/__init__.py
- src/ga4gh/core/enderef.py
- src/ga4gh/core/identifiers.py
- src/ga4gh/core/pydantic.py
- src/ga4gh/vrs/models.py
* Only focused on ga4gh.core + Pydantic models
> refactor: remove unused code + small cleanup

- .github/workflows/python-cqa.yml
- .github/workflows/release.yml
can't be having any GH actions warnings in this here repo
> cicd: update actions revs

- docs/extras/vcf_annotator.md
- src/ga4gh/vrs/extras/vcf_annotation.py
* Make the input VCF path an [argument](https://click.palletsprojects.com/en/8.1.x/arguments/) rather than an [option](https://click.palletsprojects.com/en/8.1.x/options/). I think this better matches the intent of the tool (and it was the only required option, so might as well make it an arg, right?). Left it at `nargs=1` but I think there's a case for making it `nargs=-1`... but going 1 -> -1 wouldn't be a breaking change imo so I think it's fine to put that decision off.
* pathlike args should be `click.Path`/`pathlib.Path`. Add additional configurations, like the input file must exist and the output files must be writable. Didn't make changes further up the stack because I wanted to confine this PR to just the Click interface.
* remove some superfluous/inactive configs
* Touch up help …
> feat!: enhance annotator CLI options

- docs/extras/vcf_annotator.md
- pyproject.toml
- src/ga4gh/vrs/extras/vcf_annotation.py
Declare the annotator `click` function as a console entry point, enabling `vrs-annotate input.vcf --vcf_out=out.vcf` rather than `python3 src/ga4gh/vrs/extras/vcf_annotation.py input.vcf --vcf_out=out.vcf`.
Open to suggestions on the command name. I'd prefer a structure more along the lines of `vrs-annotate vcf input.vcf --vcf_out=out.vcf` (i.e., `vrs-annotate` is the command, `vcf` is a subcommand) if we think there's a chance that other filetypes could be annotated in the future (in that case, we may want to alter the module name as well). Alternatively, though, the subcommand might be superfluous if the file argument has a suffix indicating the filetype.
> feat!: declare annotator CLI as console entrypoint

- .github/workflows/python-cqa.yml
Reece added this several years ago, but there's no `requirements.txt` file in the repo, so this doesn't do anything. Tying it to `pyproject.toml` does mean that you could have some unnecessary cache invalidations e.g. if some style configs change, but that's probably ok (and an improvement over the status quo).
> cicd: fix action caching key

- pyproject.toml
address #472 -- see explanation there. pin a non-most-recent urllib3 version until `vcrpy` merges the PR fixing compatibility.
>  test: pin urllib3 version until vcrpy is updated 

- docker-compose.yml
Docker now emits a warning when you try to use this property, and recommends its removal. See https://docs.docker.com/reference/compose-file/version-and-name/
> chore: remove obselete version property

- pyproject.toml
- src/ga4gh/vrs/extras/decorators.py
- src/ga4gh/vrs/extras/translator.py
- src/ga4gh/vrs/utils/hgvs_tools.py
with the way the translator classes do inheritance, there's a little bit of bad typing happening vis-a-vis the Variation classes, but it's hidden behind some function dispatches so Pyright at least doesn't realize it
> chore: add type annotations to hgvs tools and translator

- .github/workflows/python-cqa.yml
from the docs: https://pytest-vcr.readthedocs.io/en/latest/
> When running your tests on CI it's recommended to use the --vcr-record=none option. This way you can make sure that you have committed all the cassettes.
> test: use recommended pytest-vcr settings

- pyproject.toml
"restview" can be a helpful tool, but a) there are better alternatives (sphinx-view) and b) this isn't used in any part of the docs toolchain for this repo so I don't think it should be a declared dependency
> docs: remove restview dependency

- docs/extras/vcf_annotator.md
- pyproject.toml
- src/ga4gh/vrs/extras/annotator/__init__.py
- src/ga4gh/vrs/extras/annotator/cli.py
- src/ga4gh/vrs/extras/annotator/vcf.py
- tests/extras/test_annotate_vcf.py
* We have long bristled at the naming incongruence between `vcf_annotation.py` and `translator.py`. This makes the former consistent with the latter.
* Anticipating the possibility that we may want to annotate other kinds of files in the future, this makes `annotator` a package within `extras`, containing a `vcf` module. Also breaks the CLI into a separate module.
proposed module structure:
```
src/ga4gh/vrs/extras
├── __init__.py
├── annotator
│   ├── __init__.py
│   ├── cli.py
│   └── vcf.py
├── decorators.py
├── object_store.py
└── translator.py
```
> feat!: break annotator tools into separate submodule

- src/ga4gh/vrs/extras/annotator/vcf.py
Another easier one.
* `str.translate` is a more straightforward way to do a multi pass mapping on a string
* move consts outside of the class. It probably doesn't matter but it made more sense to me to put them there in case another module wants to refer to them.
>  feat!: move, reorganize field const variables 

- src/ga4gh/vrs/extras/annotator/vcf.py
`Logger.exception()` captures the exception name and a stack trace, so there's no need to be writing out these conditions for different exceptions that differ only by naming the exception
> refactor: condense exception annotating

- .gitmodules
- src/ga4gh/core/models.py
- src/ga4gh/vrs/models.py
- tests/validation/test_models.py
- tests/validation/test_schemas.py
close #503
* Also changes `ga4gh.keys` -> `ga4gh.inherent`
This work is needed for GKS AnVIL / ClinVar Submission
Submodule source.yaml diffs:
* https://github.com/ga4gh/gks-core/compare/064ba233eae6c9e1f914380fcf4917d300532c57...1.0.0-snapshot.2025-02.1#diff-c69e6cf4bc50458dc06f67c253a3337f9bd7522d77d8836e8d66d8b3258935a5
* https://github.com/ga4gh/vrs/compare/c9b3dd447960dec24a9e2992d7a14cc4eb5060e2...2.0.0-snapshot.2025-02.1#diff-7869e6a91abfc2ed9ce4581931d776a63caae890e9c7c83f6babeff35c2376c2
> feat!: update pydantic models to vrs 2.0.0-snapshot.2025-02

- src/ga4gh/vrs/extras/annotator/cli.py
- src/ga4gh/vrs/extras/annotator/vcf.py
- tests/extras/test_annotate_vcf.py
close #474 
Refactor the Annotator class to better support configurable outputs and side effects beyond an annotated VCF. Specifically, the class is now an Abstract Base Class, `AbstractVcfAnnotator`, and implementations must define three methods:
* `on_vrs_object`: perform filtering/transformation/side effects on VRS objects that have been translated from VCF coords. For example, attach additional extensions or mappings, or upload to a DB. Called every time the translator produces a successful VRS allele.
* Eugene had originally proposed this solely for producing side effects (like DB uploads). I thought it might be helpful to a) enable transformations/more annotations (maybe do something with the expression added by the translator, or don't pass along for VCF annotation if it meets …
> feat!: refactor annotator as ABC, add NDJSON annotation + support optional side effects

- src/ga4gh/vrs/extras/annotator/cli.py
- src/ga4gh/vrs/extras/annotator/vcf.py
Minor issue. Previously, if you forgot to add an output option, the error message you get concerns arg names passed to the `annotate()` method, not the CLI itself, so not very helpful.
I also think it might make sense to affix default behavior to the CLI (maybe just make a vcf in the current working dir) rather than raising this error, but that's a slightly bigger change.
> feat!: show more informative error msg for vcf annotate output args issue

- docs/extras/vcf_annotator.md
- src/ga4gh/vrs/extras/annotator/cli.py
the general recommendation is to use hyphens to separate words for reasons like visibility in certain terminal contexts and how some html documentation handles it. This is something we've been bad about in the past but it'd be good to get it cleaned up
> fix: use POSIX/GNU conventions for option word separators

- src/ga4gh/vrs/extras/annotator/cli.py
Unfortunate tradeoff here. We can't use a default value from `click` because that blocks the `dataproxy` module's default value resolution, so you can never get to the env var. Instead we'll include a note in the subcommand description.
> fix: ensure dataproxy env var works in CLI

- .github/workflows/python-cqa.yml
We were missing an issue upstream about a deprecated stdlib module because `setuptools` comes with an in-place fix -- but `setuptools` wasn't an explicit dependency declared for downstream users. I think we should just start with whatever `setup-python` gives us unless there's a pressing need.
> cicd: do not install setuptools

- src/ga4gh/vrs/extras/annotator/vcf.py
* VCF annotator should not collect alleles if no output is requested by user. This has major implications for memory usage, apparently.
* Provide this in a relatively OOP-friendly way without producing a breaking change
At the next major version, there is a cleaner way to do this and it should be implemented at that point
> feat: add optional suppression of allele collection

- src/ga4gh/vrs/extras/translator.py
This PR stops logging unnecessary warnings like:
```
Derived sequence '' is different from provided state.sequence 'root='''
Derived sequence 'CCCC' is different from provided state.sequence 'root='CCCC''
```
An example for reproducing the warning log. Functionality is correct, but the condition for logging has a small bug.
```python
>>> from ga4gh.vrs.extras.translator import AlleleTranslator
>>> from ga4gh.vrs.dataproxy import create_dataproxy
>>> dp = create_dataproxy('seqrepo+file:///usr/local/share/seqrepo/2024-12-20')
>>> translator = AlleleTranslator(data_proxy=dp)
>>> allele = translator.translate_from('21-5030497-C-CACCT', 'gnomad')
>>> translator.translate_to(allele, 'spdi')
Derived sequence 'ACCTACCT' is different from provided state.sequence 'root='ACCTACCT'' …
```
> fix-logging-warnings
